name: Deploy to Azure and Notify Slack
on:
  push:
    branches:
      - master # or your deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: act10ns/slack@v1

    # Your build and deploy steps go here
    
    - name: Notify Slack on Success
      if: success()
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        channel: '#test'
        message: Build and Deploy success...
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Set this in your repo secrets

    - name: Notify Slack on Failure
      if: failure()
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        channel: '#test'
        message: Build and Deploy failed...
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Set this in your repo secrets
